version: '3.7'

services:
      
    backend:
        build:
            dockerfile: Dockerfile
            context: ./backend/simple-api-student-main/
        container_name: simple_api_student
        networks:
            - app-network
        ports:
            - "8091:8080"
        depends_on:
            - database

    database:
        build:
            dockerfile: Dockerfile
            context: ./
        container_name: myPostgres
        ports:
            - "5455:5432"
        networks:
            - app-network

    httpd:
        build:
            dockerfile: Dockerfile
            context: ./HTTP/
        ports:
            - "8085:80"
        networks:
            - app-network
        depends_on:
            - backend


networks:
    app-network:
    
