#- hosts: all
#  become: yes
#  roles:
#    - httpd
#    - firewalld

- hosts: all
  gather_facts: false
  become: true
  roles:
    - docker
    - network
    - database
    - app
    - app_instance_2
    - proxy
    - grafana