name: Build and Push Docker Image
on: 
  workflow_run:
    workflows: ["Test backend"]
    types: completed
    branches: main

jobs:
      
  # define job to build and publish docker image
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    
      - name: Build image and push backend
        uses: docker/build-push-action@v5
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./backend/simple-api-student-main
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-backend-simple-api-student:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
    
      - name: Build image and push database
        uses: docker/build-push-action@v5
        with:
          context: ./
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-db:latest
          push: ${{ github.ref == 'refs/heads/main' }}
    
      - name: Build image and push httpd
        uses: docker/build-push-action@v5
        with:
          context: ./HTTP/
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-http:latest
          push: ${{ github.ref == 'refs/heads/main' }}
          
