name: Test backend

on:
  #to begin you want to launch this job in main and develop
  push:
    branches: main
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v4 
      - uses: actions/checkout@v4

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

     #finally build your app with the latest command
      - name: Build and test with Maven
        #run: mvn clean verify
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=epf-tp-devops_tp-devops -Dsonar.organization=epf-tp-devops -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: ./backend/simple-api-student-main
